version: "3"

volumes:
    mongo:
    redis:

services:
    # The app is going to run on the host machine's port 4444 in development
    nginx:
        restart: always
        depends_on:
            - express_api
            # - puzzle_client
            - gatsby
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/nginx
        ports:
            - "4444:80"

    # The main content pages are in this container
    gatsby:
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/gatsby
        # It might eventually pull data from Express, so wait for that container to boot.
        depends_on:
            - express_api
        volumes:
            - /app/node_modules
            - ./containers/gatsby:/app
        environment:
            - NODE_ENV=development
            - GATSBY_WEBPACK_PUBLICPATH=/
        working_dir: /app
        command: ./entrypoint.sh

    # The API for the puzzle server
    express_api:
        depends_on:
            - mongo
            - redis
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/express_api
        volumes:
            - /app/node_modules
            - ./containers/express_api:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - SESSION_SECRET="this is only for development"

    # The MERN database
    mongo:
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/mongo
        volumes:
            - mongo:/data/db
            - /app/node_modules
            - ./containers/mongo:/app

    # Express.js sessions
    redis:
        image: "redis:latest"
        volumes:
            - redis:/data
