# fly.toml app configuration file generated for codeselfstudy on 2026-01-06T22:09:29-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codeselfstudy"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  # "Suspended machines cost the same as stopped machines: storage only. There are no CPU/RAM charges."
  # https://fly.io/docs/reference/suspend-resume/#billing
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpus = 2
  memory_mb = 1024


